### ISSUE TITLE
前処理後のincome件数内訳がコード結果と異なる

### ISSUE THREAD

**Issue by kakuda** [ayukat1016/lightgbm_sample#10]
書籍の3.1「データ理解」の「前処理」にて、前処理後のincome件数内訳のコードを実行した結果が実際と異なります。

書籍には
```
<=50K   24720
>50K    7841
```
と記載していますが、実際にコードを実行すると結果は
```
<=50K   21999
>50K    7841
```
になります。Githubのサンプルコードでも同じ結果になっています。

https://github.com/ayukat1016/lightgbm_sample/blob/fc6f6032c4ff8baa39cb8d87d932b1771c3155f6/chapter3/section3_1_income_EDA.ipynb#L1011

書籍記載の結果を合計すると32,561件となることから、おそらく特徴量native-countryを絞る前の結果を記載しているのではないか、と思いました。ご確認よろしくお願いします。

**Comment by ayukat1016** [comment]
@kakuda 
別Issueと同様に確認します。フィードバックありがとうございます。

**Comment by ayukat1016** [comment]
@kakuda 
ご指摘ありがとうございました。正誤表に反映しました。
執筆時の見落としで、ご指摘に感謝いたします。

**Comment by kakuda** [comment]
確認＆対応いただきありがとうございました！
